# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0002_auto_20160808_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(default='b,y,a,s', max_length=7),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(default='m,f', max_length=3),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(default='s,m,l,xl', max_length=8),
        ),
    ]
