# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-09 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0004_auto_20160809_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
    ]
