# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0010_auto_20160810_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
    ]
