# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0012_auto_20160810_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='intact_or_neutered',
            field=models.CharField(choices=[('i', 'Intact'), ('n', 'Neutered')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='dog',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
