# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0013_auto_20160810_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Unknown mix', max_length=100),
        ),
    ]
